"""empty message

Revision ID: 903ea5bf8362
Revises: 5481833255ff
Create Date: 2019-12-18 16:50:36.349771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903ea5bf8362'
down_revision = '5481833255ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fromId', sa.Integer(), nullable=True),
    sa.Column('fromName', sa.String(length=120), nullable=True),
    sa.Column('fromEmail', sa.String(length=120), nullable=True),
    sa.Column('toId', sa.Integer(), nullable=True),
    sa.Column('toName', sa.String(length=120), nullable=True),
    sa.Column('toEmail', sa.String(length=120), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('dateSent', sa.String(length=120), nullable=True),
    sa.Column('read', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat')
    # ### end Alembic commands ###
